export const AttendeeConfiguration = {
    attendeeHeaders: [
        { header: 'Time Registered', field: 'time_registered' },
        { header: 'First Name', field: 'first_name' },
        { header: 'Last Name', field: 'last_name' },
        { header: 'T-Shirt Size', field: 't_shirt' },
        { header: 'Roles', field: 'role' },
        { header: 'Team', field: 'team' },
        { header: 'Room Location', field: 'room_location' },
        { header: 'Checked In Status', field: 'checked_in' },
        { header: 'Days Attending', field: 'days_attending' },
        { header: 'Gender', field: 'gender' },
        { header: 'Age', field: 'age' },
        { header: 'Medical Information', field: 'medical' },
        { header: 'Address', field: 'address' },
        { header: 'Address 2', field: 'address_2' },
        { header: 'City', field: 'city' },
        { header: 'State', field: 'state' },
        { header: 'Zip Code', field: 'zip_code' },
        { header: 'Email', field: 'email' },
        { header: 'Emergency Contact First Name', field: 'emergency_contact_first_name' },
        { header: 'Emergency Contact Last Name', field: 'emergency_contact_last_name' },
        { header: 'Emergency Contact Phone Number', field: 'emergency_contact_phone_number' },
        { header: 'Emergency Contact Relationship', field: 'emergency_contact_relationship' },
        { header: 'Church Name', field: 'your_church' },
        { header: 'Church Point Of Contact Name', field: 'your_church_point_of_contact_name' },
        { header: 'Church Point Of Contact Number', field: 'your_church_point_of_contact_number_name' },
        { header: 'Cost', field: 'cost' },
        { header: 'Paid Status', field: 'paid_status' },
        { header: 'Notes', field: 'notes' },
        { header: 'Group Leaders', field: 'group_leader' },
        { header: 'Discount Code Used', field: 'discount' }
    ]
};
